name: Fetch data and push

on:
  push:
  schedule:
    - cron:  '40 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEEP_NB_DAYS_LOGS: 45
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Cache pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run fetch
      run: |
        python fetch.py

    - name: Run aggregate
      run: |
        python aggregate.py

    - name: Run compute
      run: |
        python compute.py

    - name: Run generate
      run: |
        python generate.py

    - name: Delete old logs
      run: |
        find logs/ -type f -mtime +$KEEP_NB_DAYS_LOGS -exec rm -f {} \;

    - name: Push generated data
      if: github.ref == 'refs/heads/master'
      run: |
        git config user.email "actions@github.com"
        git config user.name "actions-user"
        git add -f logs prod
        git commit -am "New data at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        git push origin master

    - name: Move JSON file to build folder
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir build
        cp prod/all.json build/recommendations.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build
        user_name: 'actions-user'
        user_email: 'actions@github.com'
        force_orphan: true
